alias python='python3'
alias hide='/Volumes/home/Script/hide.sh'
alias extract='/Volumes/home/Script/extract.sh'
alias replace='/Volumes/home/Script/replace.sh'
alias hidive='python3 /Volumes/home/Script/hidive.py'